### ISSUE TITLE
Status-website: Github token to updating labels with insight tools

### ISSUE THREAD

**Issue by apentori** [status-im/insights-bi#16]
# Description

The Insight tools need to be able to create, read, update and delete labels.

The repositories that need to be update are  :
* status-mobile
* status-desktop
* status-go
* status-web

**Comment by apentori** [comment]
* token to create/update/delete token from specific repo: https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#update-a-label
* permission mandatory read and write permission to `issues` and `pull_requests` on the repository
* Fine grain token

To avoid issue with the rate limit, a new github issuer must be create: `status-im-tools`.

> Note: the fine grained token will have a expiration date that will implied to renew it from time to time

**Comment by apentori** [comment]
Token set to the team.
Token Valid until the 06/08/2024

@marcelines, can you confirm it's working fine ?  If so i can generate a new one with a longer validity period, to avoid expiration in the middle of august

**Comment by marcelines** [comment]
> Token set to the team. Token Valid until the 06/08/2024
> 
> @marcelines, can you confirm it's working fine ? If so i can generate a new one with a longer validity period, to avoid expiration in the middle of august

If you're referring to the one shared before, it works as expected. You can generate a new one and share it with the web team again. Thank you.

**Comment by apentori** [comment]
Token  regenerated, send via bitwarden & discord.
Expire the 30 nov 2024

**Comment by jakubgs** [comment]
Is this issue still relevant?

**Comment by apentori** [comment]
This issue can be closed
