### ISSUE TITLE
Request: Adding summary charts to the Superset Treasury Report 

### ISSUE THREAD

**Issue by AdamDynamic** [status-im/insights-bi#6]
Carl has sent me the following requests for the [Treasury Report](https://superset.bi.status.im/superset/dashboard/33/?native_filters_key=-UOW1vG_uNXP5SS1cpFUzGG1dsWArzEmEFYeH-FINOLnFPFVnYrF-JSLIW7xEEpb):

- Pie of crypto vs. non-crypto (inc and ex. community multisig)
- Pie of volatile vs. non-volatile (inc and ex. community multisig)

Can these please be added to the report?

**Comment by JoseAnaya28** [comment]
@AdamDynamic 

Added the charts on the "Asset Detail" tab of the dashboard. These are located below the asset table breakdown. Let me know if this is fine or want to move them to a different spot. 

The wallet "SNT Community" is excluded from the pie charts with "Exc. Community Multisig" on the title. Can you confirm this is what you want according to the requirement? 

<img width="1217" alt="image" src="https://github.com/status-im/insights-bi/assets/60910800/4ed23b23-5a76-4272-8c1c-f10e5536b61a">
